// Package openapitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapitypes

import (
	"encoding/json"
	"fmt"
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ApprovalInboxItem defines model for ApprovalInboxItem.
type ApprovalInboxItem struct {
	ActingAsActorId         *string                `json:"acting_as_actor_id,omitempty"`
	ApprovalRequestId       *string                `json:"approval_request_id,omitempty"`
	DecidedAt               *string                `json:"decided_at,omitempty"`
	Decision                *string                `json:"decision,omitempty"`
	DecisionByActorId       *string                `json:"decision_by_actor_id,omitempty"`
	DecisionRationale       *string                `json:"decision_rationale,omitempty"`
	RequestedAt             *string                `json:"requested_at,omitempty"`
	RequestedByActorId      *string                `json:"requested_by_actor_id,omitempty"`
	RequestedPhrase         *string                `json:"requested_phrase,omitempty"`
	RiskLevel               *string                `json:"risk_level,omitempty"`
	RiskRationale           *string                `json:"risk_rationale,omitempty"`
	Route                   *WorkflowRouteMetadata `json:"route,omitempty"`
	RunId                   *string                `json:"run_id,omitempty"`
	RunState                *string                `json:"run_state,omitempty"`
	State                   *string                `json:"state,omitempty"`
	StepCapabilityKey       *string                `json:"step_capability_key,omitempty"`
	StepId                  *string                `json:"step_id,omitempty"`
	StepName                *string                `json:"step_name,omitempty"`
	SubjectPrincipalActorId *string                `json:"subject_principal_actor_id,omitempty"`
	TaskId                  *string                `json:"task_id,omitempty"`
	TaskState               *string                `json:"task_state,omitempty"`
	TaskTitle               *string                `json:"task_title,omitempty"`
	WorkspaceId             *string                `json:"workspace_id,omitempty"`
}

// ApprovalInboxRequest defines model for ApprovalInboxRequest.
type ApprovalInboxRequest struct {
	IncludeFinal *bool   `json:"include_final,omitempty"`
	Limit        *int    `json:"limit,omitempty"`
	State        *string `json:"state,omitempty"`
	WorkspaceId  *string `json:"workspace_id,omitempty"`
}

// ApprovalInboxResponse defines model for ApprovalInboxResponse.
type ApprovalInboxResponse struct {
	Approvals   *[]ApprovalInboxItem `json:"approvals,omitempty"`
	WorkspaceId *string              `json:"workspace_id,omitempty"`
}

// ChatTurnChannelContext defines model for ChatTurnChannelContext.
type ChatTurnChannelContext struct {
	// ChannelId Canonical logical channel id (`app`, `message`, or `voice`).
	ChannelId *string `json:"channel_id,omitempty"`

	// ConnectorId Optional connector attribution for the turn context.
	ConnectorId *string `json:"connector_id,omitempty"`

	// ThreadId Optional channel-thread correlation id.
	ThreadId *string `json:"thread_id,omitempty"`
}

// ChatTurnItem defines model for ChatTurnItem.
type ChatTurnItem struct {
	ApprovalRequestId *string                 `json:"approval_request_id,omitempty"`
	Arguments         *map[string]interface{} `json:"arguments,omitempty"`
	Content           *string                 `json:"content,omitempty"`
	ErrorCode         *string                 `json:"error_code,omitempty"`
	ErrorMessage      *string                 `json:"error_message,omitempty"`
	ItemId            *string                 `json:"item_id,omitempty"`
	Metadata          *map[string]interface{} `json:"metadata,omitempty"`
	Output            *map[string]interface{} `json:"output,omitempty"`
	Role              *string                 `json:"role,omitempty"`
	Status            *string                 `json:"status,omitempty"`
	ToolCallId        *string                 `json:"tool_call_id,omitempty"`
	ToolName          *string                 `json:"tool_name,omitempty"`

	// Type Canonical turn item type (`user_message`, `assistant_message`, `tool_call`, `tool_result`, `approval_request`, `approval_decision`).
	Type *string `json:"type,omitempty"`
}

// ChatTurnRequest defines model for ChatTurnRequest.
type ChatTurnRequest struct {
	ActingAsActorId    *string                     `json:"acting_as_actor_id,omitempty"`
	Channel            *ChatTurnChannelContext     `json:"channel,omitempty"`
	Items              *[]ChatTurnItem             `json:"items,omitempty"`
	Model              *string                     `json:"model,omitempty"`
	Provider           *string                     `json:"provider,omitempty"`
	RequestedByActorId *string                     `json:"requested_by_actor_id,omitempty"`
	SubjectActorId     *string                     `json:"subject_actor_id,omitempty"`
	SystemPrompt       *string                     `json:"system_prompt,omitempty"`
	TaskClass          *string                     `json:"task_class,omitempty"`
	ToolCatalog        *[]ChatTurnToolCatalogEntry `json:"tool_catalog,omitempty"`
	WorkspaceId        *string                     `json:"workspace_id,omitempty"`
}

// ChatTurnResponse defines model for ChatTurnResponse.
type ChatTurnResponse struct {
	Channel                      *ChatTurnChannelContext     `json:"channel,omitempty"`
	ContractVersion              *string                     `json:"contract_version,omitempty"`
	CorrelationId                *string                     `json:"correlation_id,omitempty"`
	Items                        *[]ChatTurnItem             `json:"items,omitempty"`
	ModelKey                     *string                     `json:"model_key,omitempty"`
	Provider                     *string                     `json:"provider,omitempty"`
	RealtimeEventContractVersion *string                     `json:"realtime_event_contract_version,omitempty"`
	TaskClass                    *string                     `json:"task_class,omitempty"`
	TaskRunCorrelation           *ChatTurnTaskRunCorrelation `json:"task_run_correlation,omitempty"`
	TurnItemSchemaVersion        *string                     `json:"turn_item_schema_version,omitempty"`
	WorkspaceId                  *string                     `json:"workspace_id,omitempty"`
}

// ChatTurnTaskRunCorrelation defines model for ChatTurnTaskRunCorrelation.
type ChatTurnTaskRunCorrelation struct {
	Available *bool   `json:"available,omitempty"`
	RunId     *string `json:"run_id,omitempty"`
	RunState  *string `json:"run_state,omitempty"`
	Source    *string `json:"source,omitempty"`
	TaskId    *string `json:"task_id,omitempty"`
	TaskState *string `json:"task_state,omitempty"`
}

// ChatTurnToolCatalogEntry defines model for ChatTurnToolCatalogEntry.
type ChatTurnToolCatalogEntry struct {
	CapabilityKeys *[]string               `json:"capability_keys,omitempty"`
	Description    *string                 `json:"description,omitempty"`
	InputSchema    *map[string]interface{} `json:"input_schema,omitempty"`
	Name           *string                 `json:"name,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	CorrelationId string `json:"correlation_id"`
	Detail        string `json:"detail"`
	Error         struct {
		Code string `json:"code"`

		// Details Optional domain-specific typed error metadata.
		// For `service_not_configured` errors this includes `category`,
		// `service` (`id`, `label`, `config_field`), `domain`, and `remediation`
		// (`action`, `label`, `hint`).
		Details *interface{} `json:"details,omitempty"`
		Message string       `json:"message"`
	} `json:"error"`
	Instance             string                 `json:"instance"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ModelDiscoverItem defines model for ModelDiscoverItem.
type ModelDiscoverItem struct {
	DisplayName *string `json:"display_name,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`
	InCatalog   *bool   `json:"in_catalog,omitempty"`
	ModelKey    *string `json:"model_key,omitempty"`
	Provider    *string `json:"provider,omitempty"`
	Source      *string `json:"source,omitempty"`
}

// ModelDiscoverProviderResult defines model for ModelDiscoverProviderResult.
type ModelDiscoverProviderResult struct {
	Message          *string              `json:"message,omitempty"`
	Models           *[]ModelDiscoverItem `json:"models,omitempty"`
	Provider         *string              `json:"provider,omitempty"`
	ProviderEndpoint *string              `json:"provider_endpoint,omitempty"`
	ProviderReady    *bool                `json:"provider_ready,omitempty"`
	Success          *bool                `json:"success,omitempty"`
}

// ModelDiscoverRequest defines model for ModelDiscoverRequest.
type ModelDiscoverRequest struct {
	Provider    *string `json:"provider,omitempty"`
	WorkspaceId *string `json:"workspace_id,omitempty"`
}

// ModelDiscoverResponse defines model for ModelDiscoverResponse.
type ModelDiscoverResponse struct {
	Results     *[]ModelDiscoverProviderResult `json:"results,omitempty"`
	WorkspaceId *string                        `json:"workspace_id,omitempty"`
}

// ModelListItem defines model for ModelListItem.
type ModelListItem struct {
	Enabled          *bool   `json:"enabled,omitempty"`
	ModelKey         *string `json:"model_key,omitempty"`
	Provider         *string `json:"provider,omitempty"`
	ProviderEndpoint *string `json:"provider_endpoint,omitempty"`
	ProviderReady    *bool   `json:"provider_ready,omitempty"`
	WorkspaceId      *string `json:"workspace_id,omitempty"`
}

// ModelListRequest defines model for ModelListRequest.
type ModelListRequest struct {
	Provider    *string `json:"provider,omitempty"`
	WorkspaceId *string `json:"workspace_id,omitempty"`
}

// ModelListResponse defines model for ModelListResponse.
type ModelListResponse struct {
	Models      *[]ModelListItem `json:"models,omitempty"`
	WorkspaceId *string          `json:"workspace_id,omitempty"`
}

// ModelRouteDecision defines model for ModelRouteDecision.
type ModelRouteDecision struct {
	Decision   *string `json:"decision,omitempty"`
	ModelKey   *string `json:"model_key,omitempty"`
	Note       *string `json:"note,omitempty"`
	Provider   *string `json:"provider,omitempty"`
	ReasonCode *string `json:"reason_code,omitempty"`
	Step       *string `json:"step,omitempty"`
}

// ModelRouteExplainRequest defines model for ModelRouteExplainRequest.
type ModelRouteExplainRequest struct {
	PrincipalActorId *string `json:"principal_actor_id,omitempty"`
	TaskClass        *string `json:"task_class,omitempty"`
	WorkspaceId      *string `json:"workspace_id,omitempty"`
}

// ModelRouteExplainResponse defines model for ModelRouteExplainResponse.
type ModelRouteExplainResponse struct {
	Decisions        *[]ModelRouteDecision         `json:"decisions,omitempty"`
	Explanations     *[]string                     `json:"explanations,omitempty"`
	FallbackChain    *[]ModelRouteFallbackDecision `json:"fallback_chain,omitempty"`
	PrincipalActorId *string                       `json:"principal_actor_id,omitempty"`
	ReasonCodes      *[]string                     `json:"reason_codes,omitempty"`
	SelectedModelKey *string                       `json:"selected_model_key,omitempty"`
	SelectedProvider *string                       `json:"selected_provider,omitempty"`
	SelectedSource   *string                       `json:"selected_source,omitempty"`
	Summary          *string                       `json:"summary,omitempty"`
	TaskClass        *string                       `json:"task_class,omitempty"`
	WorkspaceId      *string                       `json:"workspace_id,omitempty"`
}

// ModelRouteFallbackDecision defines model for ModelRouteFallbackDecision.
type ModelRouteFallbackDecision struct {
	ModelKey   *string `json:"model_key,omitempty"`
	Provider   *string `json:"provider,omitempty"`
	Rank       *int    `json:"rank,omitempty"`
	ReasonCode *string `json:"reason_code,omitempty"`
	Selected   *bool   `json:"selected,omitempty"`
}

// ProviderCheckItem defines model for ProviderCheckItem.
type ProviderCheckItem struct {
	Endpoint   *string `json:"endpoint,omitempty"`
	LatencyMs  *int64  `json:"latency_ms,omitempty"`
	Message    *string `json:"message,omitempty"`
	Provider   *string `json:"provider,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
	Success    *bool   `json:"success,omitempty"`
}

// ProviderCheckRequest defines model for ProviderCheckRequest.
type ProviderCheckRequest struct {
	Provider    *string `json:"provider,omitempty"`
	WorkspaceId *string `json:"workspace_id,omitempty"`
}

// ProviderCheckResponse defines model for ProviderCheckResponse.
type ProviderCheckResponse struct {
	Results     *[]ProviderCheckItem `json:"results,omitempty"`
	Success     *bool                `json:"success,omitempty"`
	WorkspaceId *string              `json:"workspace_id,omitempty"`
}

// ProviderConfigRecord defines model for ProviderConfigRecord.
type ProviderConfigRecord struct {
	ApiKeyConfigured *bool      `json:"api_key_configured,omitempty"`
	ApiKeySecretName *string    `json:"api_key_secret_name,omitempty"`
	Endpoint         *string    `json:"endpoint,omitempty"`
	Provider         *string    `json:"provider,omitempty"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
	WorkspaceId      *string    `json:"workspace_id,omitempty"`
}

// ProviderListRequest defines model for ProviderListRequest.
type ProviderListRequest struct {
	WorkspaceId *string `json:"workspace_id,omitempty"`
}

// ProviderListResponse defines model for ProviderListResponse.
type ProviderListResponse struct {
	Providers   *[]ProviderConfigRecord `json:"providers,omitempty"`
	WorkspaceId *string                 `json:"workspace_id,omitempty"`
}

// ProviderSetRequest defines model for ProviderSetRequest.
type ProviderSetRequest struct {
	ApiKeySecretName *string `json:"api_key_secret_name,omitempty"`
	ClearApiKey      *bool   `json:"clear_api_key,omitempty"`
	Endpoint         *string `json:"endpoint,omitempty"`
	Provider         *string `json:"provider,omitempty"`
	WorkspaceId      *string `json:"workspace_id,omitempty"`
}

// TaskRunActionAvailability defines model for TaskRunActionAvailability.
type TaskRunActionAvailability struct {
	CanCancel  bool `json:"can_cancel"`
	CanRequeue bool `json:"can_requeue"`
	CanRetry   bool `json:"can_retry"`
}

// TaskRunListItem defines model for TaskRunListItem.
type TaskRunListItem struct {
	ActingAsActorId         *string                    `json:"acting_as_actor_id,omitempty"`
	Actions                 *TaskRunActionAvailability `json:"actions,omitempty"`
	FinishedAt              *string                    `json:"finished_at,omitempty"`
	LastError               *string                    `json:"last_error,omitempty"`
	Priority                *int                       `json:"priority,omitempty"`
	RequestedByActorId      *string                    `json:"requested_by_actor_id,omitempty"`
	Route                   *WorkflowRouteMetadata     `json:"route,omitempty"`
	RunCreatedAt            *string                    `json:"run_created_at,omitempty"`
	RunId                   *string                    `json:"run_id,omitempty"`
	RunState                *string                    `json:"run_state,omitempty"`
	RunUpdatedAt            *string                    `json:"run_updated_at,omitempty"`
	StartedAt               *string                    `json:"started_at,omitempty"`
	SubjectPrincipalActorId *string                    `json:"subject_principal_actor_id,omitempty"`
	TaskCreatedAt           *string                    `json:"task_created_at,omitempty"`
	TaskId                  *string                    `json:"task_id,omitempty"`
	TaskState               *string                    `json:"task_state,omitempty"`
	TaskUpdatedAt           *string                    `json:"task_updated_at,omitempty"`
	Title                   *string                    `json:"title,omitempty"`
	WorkspaceId             *string                    `json:"workspace_id,omitempty"`
}

// TaskRunListRequest defines model for TaskRunListRequest.
type TaskRunListRequest struct {
	Limit       *int    `json:"limit,omitempty"`
	State       *string `json:"state,omitempty"`
	WorkspaceId *string `json:"workspace_id,omitempty"`
}

// TaskRunListResponse defines model for TaskRunListResponse.
type TaskRunListResponse struct {
	Items       *[]TaskRunListItem `json:"items,omitempty"`
	WorkspaceId *string            `json:"workspace_id,omitempty"`
}

// TaskSubmitRequest defines model for TaskSubmitRequest.
type TaskSubmitRequest struct {
	Description             *string `json:"description,omitempty"`
	RequestedByActorId      string  `json:"requested_by_actor_id"`
	SubjectPrincipalActorId string  `json:"subject_principal_actor_id"`
	TaskClass               *string `json:"task_class,omitempty"`
	Title                   string  `json:"title"`
	WorkspaceId             string  `json:"workspace_id"`
}

// TaskSubmitResponse defines model for TaskSubmitResponse.
type TaskSubmitResponse struct {
	CorrelationId string `json:"correlation_id"`
	RunId         string `json:"run_id"`
	State         string `json:"state"`
	TaskId        string `json:"task_id"`
}

// WorkflowRouteMetadata defines model for WorkflowRouteMetadata.
type WorkflowRouteMetadata struct {
	Available       *bool   `json:"available,omitempty"`
	ModelKey        *string `json:"model_key,omitempty"`
	Notes           *string `json:"notes,omitempty"`
	Provider        *string `json:"provider,omitempty"`
	RouteSource     *string `json:"route_source,omitempty"`
	TaskClass       *string `json:"task_class,omitempty"`
	TaskClassSource *string `json:"task_class_source,omitempty"`
}

// CorrelationID defines model for CorrelationID.
type CorrelationID = string

// BadRequestApplicationJSON defines model for BadRequest.
type BadRequestApplicationJSON = ErrorResponse

// BadRequestApplicationProblemPlusJSON defines model for BadRequest.
type BadRequestApplicationProblemPlusJSON = ErrorResponse

// NotImplementedApplicationJSON defines model for NotImplemented.
type NotImplementedApplicationJSON = ErrorResponse

// NotImplementedApplicationProblemPlusJSON defines model for NotImplemented.
type NotImplementedApplicationProblemPlusJSON = ErrorResponse

// UnauthorizedApplicationJSON defines model for Unauthorized.
type UnauthorizedApplicationJSON = ErrorResponse

// UnauthorizedApplicationProblemPlusJSON defines model for Unauthorized.
type UnauthorizedApplicationProblemPlusJSON = ErrorResponse

// ApprovalInboxListParams defines parameters for ApprovalInboxList.
type ApprovalInboxListParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// ChatTurnParams defines parameters for ChatTurn.
type ChatTurnParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// ModelDiscoverParams defines parameters for ModelDiscover.
type ModelDiscoverParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// ModelListParams defines parameters for ModelList.
type ModelListParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// ModelRouteExplainParams defines parameters for ModelRouteExplain.
type ModelRouteExplainParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// ProviderCheckParams defines parameters for ProviderCheck.
type ProviderCheckParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// ProviderListParams defines parameters for ProviderList.
type ProviderListParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// ProviderSetParams defines parameters for ProviderSet.
type ProviderSetParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// SubmitTaskParams defines parameters for SubmitTask.
type SubmitTaskParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// TaskRunListParams defines parameters for TaskRunList.
type TaskRunListParams struct {
	// XCorrelationID Optional correlation ID propagated across daemon responses/events.
	XCorrelationID *CorrelationID `json:"X-Correlation-ID,omitempty"`
}

// ApprovalInboxListJSONRequestBody defines body for ApprovalInboxList for application/json ContentType.
type ApprovalInboxListJSONRequestBody = ApprovalInboxRequest

// ChatTurnJSONRequestBody defines body for ChatTurn for application/json ContentType.
type ChatTurnJSONRequestBody = ChatTurnRequest

// ModelDiscoverJSONRequestBody defines body for ModelDiscover for application/json ContentType.
type ModelDiscoverJSONRequestBody = ModelDiscoverRequest

// ModelListJSONRequestBody defines body for ModelList for application/json ContentType.
type ModelListJSONRequestBody = ModelListRequest

// ModelRouteExplainJSONRequestBody defines body for ModelRouteExplain for application/json ContentType.
type ModelRouteExplainJSONRequestBody = ModelRouteExplainRequest

// ProviderCheckJSONRequestBody defines body for ProviderCheck for application/json ContentType.
type ProviderCheckJSONRequestBody = ProviderCheckRequest

// ProviderListJSONRequestBody defines body for ProviderList for application/json ContentType.
type ProviderListJSONRequestBody = ProviderListRequest

// ProviderSetJSONRequestBody defines body for ProviderSet for application/json ContentType.
type ProviderSetJSONRequestBody = ProviderSetRequest

// SubmitTaskJSONRequestBody defines body for SubmitTask for application/json ContentType.
type SubmitTaskJSONRequestBody = TaskSubmitRequest

// TaskRunListJSONRequestBody defines body for TaskRunList for application/json ContentType.
type TaskRunListJSONRequestBody = TaskRunListRequest

// Getter for additional properties for ErrorResponse. Returns the specified
// element and whether it was found
func (a ErrorResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorResponse
func (a *ErrorResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorResponse to handle AdditionalProperties
func (a *ErrorResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["correlation_id"]; found {
		err = json.Unmarshal(raw, &a.CorrelationId)
		if err != nil {
			return fmt.Errorf("error reading 'correlation_id': %w", err)
		}
		delete(object, "correlation_id")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorResponse to handle AdditionalProperties
func (a ErrorResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["correlation_id"], err = json.Marshal(a.CorrelationId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'correlation_id': %w", err)
	}

	object["detail"], err = json.Marshal(a.Detail)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'detail': %w", err)
	}

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	object["instance"], err = json.Marshal(a.Instance)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'instance': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
